version: "3"
services: 
    nginx:
        ports:
            - "3000:80"
    node-app:
        build:
            context: .
            args:  #args for dockerfile to npm install according to env
                NODE_ENV: development
        volumes: 
            - ./:/app
            - /app/node_modules
        environment:
            - NODE_ENV=development
            - MONGO_USER=root
            - MONGO_PASSWORD=example
            - REDIS_PORT=6379
            - SESSION_SECRET=jhbr3j2b23ro1rf9if2rf243
        command: npm run dev

    nodev2:
        build: 
            context: ../server2
            args:  #args for dockerfile to npm install according to env
                NODE_ENV: development
        volumes: 
            - ../server2:/server2
            - /server2/node_modules
        environment:
            - NODE_ENV=development
        command: npm run dev
